name: my_premier_league_app
description: "A final Flutter project for EPL standings, news, and match information."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- HIVE DATABASE ---
  hive: ^2.1.0 
  hive_flutter: ^1.1.0 
  
  # --- Login & Utilities ---
  crypto: ^3.0.3           
  shared_preferences: ^2.2.2 

  # --- API & External ---
  http: ^1.1.2             
  url_launcher: ^6.2.2     
  
  # --- LBS & Time ---
  geolocator: ^11.0.0      
  timezone: ^0.9.2         

  # --- Notifications ---
  # Bump flutter_local_notifications to a newer patch/minor version to pick up
  # fixes for Android compile issues (ambiguous bigLargeIcon overloads).
  # Use the latest available minor/patch request that exists in your local
  # pub cache. 16.3.3 is known to be present; keep the constraint permissive.
  flutter_local_notifications: ^16.3.3
  flutter_svg: ^2.0.9      
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/home.svg
    - assets/icons/standings.svg
    - assets/icons/event.svg
    - assets/icons/trophy.svg
    - assets/icons/swap.svg
    - assets/icons/profile.svg
    - assets/Berita Arsenal.jpeg
    - assets/Casemiro.jpg
    - assets/Camavinga.jpeg
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Wajib untuk Hive 
  build_runner: ^2.4.6 
  hive_generator: ^2.0.1